# Generated by Django 6.0.6 on 2026-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('romance', '로맨스/멜로'), ('comedy', '코미디'), ('thriller', '스릴러/공포'), ('sf', 'SF/판타지'), ('drama', '드라마'), ('animation', '애니메이션')], default='drama', max_length=50),
        ),
    ]
